version: '3'
services:
  cat_application_consumer:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: cat_application/consumer
    ports:
      - '8081:8080'
    environment:
      ADDITIONAL_OPTS: '-Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m'
      PROFILE: 'dev'
    links:
      - db
    depends_on:
      - db
    networks:
      - cat-network

  db:
    image: mysql:5.6
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'catsdb'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - cat-network

networks:
  cat-network:
    driver: bridge